CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE TABLE dbo."DeviceCodes" (
        "UserCode" character varying(200) NOT NULL,
        "DeviceCode" character varying(200) NOT NULL,
        "SubjectId" character varying(200) NULL,
        "SessionId" character varying(100) NULL,
        "ClientId" character varying(200) NOT NULL,
        "Description" character varying(200) NULL,
        "CreationTime" timestamp with time zone NOT NULL,
        "Expiration" timestamp with time zone NOT NULL,
        "Data" character varying(50000) NOT NULL,
        CONSTRAINT "PK_DeviceCodes" PRIMARY KEY ("UserCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE TABLE dbo."Keys" (
        "Id" character varying(450) NOT NULL,
        "Version" integer NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Use" character varying(450) NULL,
        "Algorithm" character varying(100) NOT NULL,
        "IsX509Certificate" boolean NOT NULL,
        "DataProtected" boolean NOT NULL,
        "Data" text NOT NULL,
        CONSTRAINT "PK_Keys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE TABLE dbo."PersistedGrants" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(200) NULL,
        "Type" character varying(50) NOT NULL,
        "SubjectId" character varying(200) NULL,
        "SessionId" character varying(100) NULL,
        "ClientId" character varying(200) NOT NULL,
        "Description" character varying(200) NULL,
        "CreationTime" timestamp with time zone NOT NULL,
        "Expiration" timestamp with time zone NULL,
        "ConsumedTime" timestamp with time zone NULL,
        "Data" character varying(50000) NOT NULL,
        CONSTRAINT "PK_PersistedGrants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE TABLE dbo."PushedAuthorizationRequests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReferenceValueHash" character varying(64) NOT NULL,
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "Parameters" text NOT NULL,
        CONSTRAINT "PK_PushedAuthorizationRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE TABLE dbo."ServerSideSessions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "Scheme" character varying(100) NOT NULL,
        "SubjectId" character varying(100) NOT NULL,
        "SessionId" character varying(100) NULL,
        "DisplayName" character varying(100) NULL,
        "Created" timestamp with time zone NOT NULL,
        "Renewed" timestamp with time zone NOT NULL,
        "Expires" timestamp with time zone NULL,
        "Data" text NOT NULL,
        CONSTRAINT "PK_ServerSideSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_DeviceCodes_DeviceCode" ON dbo."DeviceCodes" ("DeviceCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_DeviceCodes_Expiration" ON dbo."DeviceCodes" ("Expiration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_Keys_Use" ON dbo."Keys" ("Use");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_ConsumedTime" ON dbo."PersistedGrants" ("ConsumedTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_Expiration" ON dbo."PersistedGrants" ("Expiration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_PersistedGrants_Key" ON dbo."PersistedGrants" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_SubjectId_ClientId_Type" ON dbo."PersistedGrants" ("SubjectId", "ClientId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_SubjectId_SessionId_Type" ON dbo."PersistedGrants" ("SubjectId", "SessionId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_PushedAuthorizationRequests_ReferenceValueHash" ON dbo."PushedAuthorizationRequests" ("ReferenceValueHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_DisplayName" ON dbo."ServerSideSessions" ("DisplayName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_Expires" ON dbo."ServerSideSessions" ("Expires");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_ServerSideSessions_Key" ON dbo."ServerSideSessions" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_SessionId" ON dbo."ServerSideSessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_SubjectId" ON dbo."ServerSideSessions" ("SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124101518_AddIdentityServerOperationalStore') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251124101518_AddIdentityServerOperationalStore', '8.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20251124140311_MoveToDbOSchema') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251124140311_MoveToDbOSchema', '8.0.0');
    END IF;
END $EF$;

COMMIT;

